# Site settings
title: Michael Liu
email: michaelangeliu+blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soon to be a compiled source of everything Michael Liu wants you
  to know about himself. He's a renaissance man of the modern era.
  Web developer. Aspiring Polyglot. Violinist. Dancer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: michaelangeliu
github_username:  michaelangeliu
facebook_username: michaelangeliu
tumblr_username:  michaelangeliu

# Collections
collections: 
- collection_quotes

# Build settings
markdown: kramdown
